// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Repro.Runtime")>]
[<assembly: AssemblyProductAttribute("Repro")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Repro.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Repro.Runtime"
    let [<Literal>] AssemblyProduct = "Repro"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Repro."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
